language: py2
script:
  - sudo pip install -r requirements.txt
  - sudo apt-get install nginx ruby -y
  - erb /vagrant/nginx.conf > /vagrant/nginx.conf~
  - sudo rm /etc/nginx/sites-enabled/default
  - sudo rm /etc/nginx/sites-available/default
  - sudo cp /vagrant/nginx.conf~ /etc/nginx/sites-available/default
  - sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
  - sudo service nginx stop
  - sudo service nginx start
  - sudo rm /tmp/uwsgi.sock -rf
  - uwsgi --processes 4 -s /tmp/uwsgi.sock --wsgi-file /vagrant/app.py --callable app --chmod-socket=666 -d /tmp/uwsgi.log
  - sleep 1
  - ls /tmp
  - cat /tmp/uwsgi.log
  #- uwsgi --processes 4 --http "$APP_HOST:$APP_PORT" --wsgi-file /vagrant/app.py --callable app
