language: go
script:
  # the connection to github is not stable, so I downloaded the dependencies and put them in the git repo.
  #- export GOPATH=$(pwd):$GOPATH && go get
  - export GOPATH=$(pwd):$GOPATH && go run main.go
